/* ***********************************************
 * whatsPlaying
 * Copyright (C) Greg Brown, All rights reserved.
 * https://github.com/gregtbrown/whatsPlaying
 * ***********************************************/

// *** DO NOT EDIT THIS FILE ***
// this file is for reference ONLY and NOT used by this app
// copy this file to the required 'myconfig.js' and make edits there

exports.debug = false;  // show debugging msgs
//exports.ip = ;  // IP address to listen on, defaults to host name
exports.port = 8000;  // port to listen on, defaults to 80
exports.clientId = "<your spotify client ID>";  // spotify account client ID
exports.clientSecret = "<your spotify client secret>";  // spotify account client secret
